---
title: "class07"
author: "Felipe Rangel"
date: "1/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## funnction revisit 

```{r}
source("http://tinyurl.com/rescale-R")
```

```{r}
rescale <- function(x, na.rm=TRUE, plot=FALSE, ...) {
 rng <-range(x, na.rm=na.rm)

 answer <- (x - rng[1]) / (rng[2] - rng[1])
 if(plot) {
 plot(answer, ...)
 }
 return(answer)
}
```

#Let's try the rescale() function out

```{r}
rescale(c(1,5,10))
```
lET'S try **rescale2()** with the **stop()** function catch for non-numeric input
```{r}
#rescale2(c(1:5, "string"))

```
**which(is.na())**
```{r}
x <- c(3,7,NA,6,9)
which(is.na(x))
```
**is.na**
```
{r}
x <- c(3,7,NA,6,9)
is.na(x)
```

```{r}
# Lets define an example x and y
x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)

```

```{r}
#is.na(xy)
```
### 
 # Lets define an example x and y
> x <- c( 1, 2, NA, 3, NA)
> y <- c(NA, 3, NA, 3, 4)
> 
> is.na(x)
[1] FALSE FALSE  TRUE FALSE  TRUE

> sum( is.na(x) )
[1] 2

> # Putting together!
> sum( is.na(x) & is.na(y) )
[1] 1 
###

```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)

both_na(x, y1)
```

## **==** **!=**
```{r}
5==5
5!=6
```

```{r}
#both_na2(x,y2)
```

```{r}
both_na3 <- function(x, y) {
 if(length(x) != length(y)) {
 stop("Input x and y should be vectors of the same length")
 }

 na.in.both <- ( is.na(x) & is.na(y) )
 na.number <- sum(na.in.both)
 na.which <- which(na.in.both)
 message("Found ", na.number, " NA's at position(s):",
 paste(na.which, collapse=", ") )

 return( list(number=na.number, which=na.which) )
}
```

```{r}
both_na3(x,y1)
```
##ggbio##
```{r}
x <- c(1:50)

```
```{r}
library(ggplot2)

theme_set(theme_bw())

hc <- hclust(dist(USArrests), "ave")  # hierarchical clustering

# plot
#ggdendrogram(hc, rotate = TRUE, size = 2)


```

